/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoAppCRUD;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {

    public static void main(String[] args) throws SQLException {

        /*
        
        //Criando um novo projeto
        ProjectController projectController = new ProjectController();
        Project project = new Project();
        project.setName("Projeto teste7");
        project.setDescription("description7");
        projectController.save(project);
        */
        
        /*
        //Atualizando o nome e descricao de um projeto existente
        ProjectController projectController = new ProjectController();
        Project project = new Project();
        project.setId(7);
        project.setName("Novo nome de projetoaaaa");
        project.setDescription("descriptionaaaa7");
        projectController.update(project);
        */

        /*
        //Dando getAll pra printa no console quantos projetos existem
        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
        */
        
        /*
        //Delete by id
        projectController.removeById(7);
        */
        
        //============================================\\
        TaskController taskController = new TaskController();
        
        /*
        //Criar uma nova task
        Task task = new Task();
        task.setIdProject(2);
        task.setName("Criar as telas de aplicação");
        task.setDescription("Devem ser criadas telas para os cadastros");
        task.setNotes("sem notas");
        task.setIsCompleted(false);
        task.setDeadline(new Date());        
        taskController.save(task);
        */
        
        /*
        //Renomear uma task
        task.setName("alterar telas da aplicação");
        taskController.update(task);
        */
        
        /*
        //GetAll
        List<Task> tasks = taskController.getAll(2);
        System.out.println("Total de tarefas = " + tasks.size());
        */
    }   
}
